services:
  - type: web
    name: verifai-platform
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NVIDIA_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CX
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
